#
###################################
# Site wide configuration
####################################
#
title: Annie Ke
email: annieke8@gmail.com
description: Annie Ke's personal site
url: # the base hostname & protocol for your site
keywords: ["annie ke", "annie", "ke"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Pacific Daylight Time
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /posts/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Annie Ke
  avatar: avatar.jpg
  job: "Software, politics, new + old stuff"
  bio: "Hello I'm Annie!! I like people, technology, and nature (minus mosquitoes)."
  email: annieke8@gmail.com
  twitter: annieYke
  github: annieke
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: annieke
  medium: annieke
